name: Cascading auto-merge Main to Develop

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetches all history for all branches

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: List branches
        run: git branch -a

      - name: Checkout development branch
        run: git checkout Development

      - name: Merge main into Development (ff-only)
        run: |
          git fetch origin main
          git merge --ff-only origin/main

      - name: Push changes
        run: git push origin Development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
