name: .NET Core Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: Backend/Messegify/Messegify.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}

      # Build the solution
      - name: Build the solution
        run: dotnet build ${{ env.Solution_Name }} --no-restore --configuration ${{ matrix.configuration }}

      # Execute unit tests and generate combined report
      - name: Execute unit tests
        run: dotnet test ${{ env.Solution_Name }} --no-build --configuration ${{ matrix.configuration }} --logger "trx;LogFileName=test-results.trx"

      # Install reportgenerator tool
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      # Combine test results into a single report
      - name: Combine test results
        run: reportgenerator -reports:**/TestResults/test-results.trx -targetdir:TestResults -reporttypes:HtmlInline_AzurePipelines

      # Publish test results
      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults
